### ISSUE TITLE
Crash App, Resources NotFoundException

### ISSUE THREAD

**Issue by syarihu** [DroidKaigi/conference-app-2017#123]
## Overview (Required)
- Device: Nexus 5X (Android 7.1.2)
- Entering "ya" in the search field will crash with "a".
- Xperia Z3 Compact (Android 6.0) did not crash.

## Screenshot
```
02-06 22:07:51.839 21448-21448/io.github.droidkaigi.confsched2017.develop.debug E/UncaughtException: android.content.res.Resources$NotFoundException: Drawable io.github.droidkaigi.confsched2017.develop.debug:drawable/ic_speaker_12_vector with resource ID #0x7f020073
                                                                                                     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_speaker_12_vector.xml from drawable resource ID #0x7f020073
                                                                                                         at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:725)
                                                                                                         at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
                                                                                                         at android.content.res.Resources.getDrawable(Resources.java:771)
                                                                                                         at android.content.Context.getDrawable(Context.java:525)
                                                                                                         at android.support.v4.content.ContextCompatApi21.getDrawable(ContextCompatApi21.java:30)
                                                                                                         at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:372)
                                                                                                         at io.github.droidkaigi.confsched2017.view.helper.DataBindingHelper.setSearchResultIcon(DataBindingHelper.java:206)
                                                                                                         at io.github.droidkaigi.confsched2017.databinding.ViewSearchResultBinding.executeBindings(ViewSearchResultBinding.java:136)
                                                                                                         at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:355)
                                                                                                         at io.github.droidkaigi.confsched2017.view.fragment.SearchFragment$SearchResultsAdapter.onBindViewHolder(SearchFragment.java:181)
                                                                                                         at io.github.droidkaigi.confsched2017.view.fragment.SearchFragment$SearchResultsAdapter.onBindViewHolder(SearchFragment.java:148)
                                                                                                         at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6308)
                                                                                                         at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6341)
                                                                                                         at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5287)
                                                                                                         at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5550)
                                                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5392)
                                                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5388)
                                                                                                         at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                                                         at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
                                                                                                         at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                                                                         at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
                                                                                                         at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3535)
                                                                                                         at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2979)
                                                                                                         at android.view.View.measure(View.java:19857)
                                                                                                         at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                                                         at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                                                         at android.view.View.measure(View.java:19857)
                                                                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                                         at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                                         at android.view.View.measure(View.java:19857)
                                                                                                         at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                                                         at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                                                         at android.view.View.measure(View.java:19857)
                                                                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                                         at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                                         at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                                                         at android.view.View.measure(View.java:19857)
                                                                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                                         at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                                         at android.view.View.measure(View.java:19857)
                                                                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                                         at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                                         at android.view.View.measure(View.java:19857)
                                                                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                                         at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                                                         at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
02-06 22:07:51.839 21448-21448/io.github.droidkaigi.confsched2017.develop.debug E/UncaughtException:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                                                         at android.view.View.measure(View.java:19857)
                                                                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                                         at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                                         at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
                                                                                                         at android.view.View.measure(View.java:19857)
                                                                                                         at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
                                                                                                         at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
                                                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
                                                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
                                                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                                         at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                                                      Caused by: java.lang.IllegalArgumentException: Path string cannot be empty.
                                                                                                         at android.util.PathParser.nCreatePathDataFromString(Native Method)
                                                                                                         at android.util.PathParser.-wrap1(PathParser.java)
                                                                                                         at android.util.PathParser$PathData.<init>(PathParser.java:74)
                                                                                                         at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:1883)
                                                                                                         at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1834)
                                                                                                         at android.graphics.drawable.VectorDrawable.inflateChildElements(VectorDrawable.java:727)
                                                                                                         at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:628)
                                                                                                         at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:130)
                                                                                                         at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1227)
                                                                                                         at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1200)
                                                                                                         at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:715)
                                                                                                         	... 67 more
```

**Comment by konifar** [comment]
Thank you for report!
Maybe this was fixed by @takahirom 😉 
https://github.com/DroidKaigi/conference-app-2017/pull/119

If this is was fixed by this PR, please close this 🙇

**Comment by syarihu** [comment]
@konifar 
oh...sorry, I did not notice it...
I confirm it!

**Comment by syarihu** [comment]
It was fixed!
Thank you!
