### ISSUE TITLE
Crashed when saving debug menu

### ISSUE THREAD

**Issue by hkurokawa** [DroidKaigi/conference-app-2017#254]
## Overview (Required)
Firebase Analytics reported a below error.

<details>
<code>
<pre>
Exception java.lang.RuntimeException: Parcel: unable to marshal value com.tomoima.debot.strategy.CheckDpiStrategy@772b526
android.os.Parcel.writeValue (Parcel.java:1481)
android.os.Parcel.writeList (Parcel.java:816)
android.os.Parcel.writeValue (Parcel.java:1428)
android.os.Parcel.writeArrayMapInternal (Parcel.java:728)
android.os.BaseBundle.writeToParcelInner (BaseBundle.java:1408)
android.os.Bundle.writeToParcel (Bundle.java:1133)
android.os.Parcel.writeBundle (Parcel.java:768)
android.support.v4.app.FragmentState.writeToParcel (Fragment.java:148)
android.os.Parcel.writeTypedArray (Parcel.java:1311)
android.support.v4.app.FragmentManagerState.writeToParcel (FragmentManager.java:564)
android.os.Parcel.writeParcelable (Parcel.java:1500)
android.os.Parcel.writeValue (Parcel.java:1406)
android.os.Parcel.writeArrayMapInternal (Parcel.java:728)
android.os.BaseBundle.writeToParcelInner (BaseBundle.java:1408)
android.os.Bundle.writeToParcel (Bundle.java:1133)
android.os.Parcel.writeBundle (Parcel.java:768)
android.app.ActivityManagerProxy.activityStopped (ActivityManagerNative.java:3627)
android.app.ActivityThread$StopInfo.run (ActivityThread.java:3850)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:241)
android.app.ActivityThread.main (ActivityThread.java:6223)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:865)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:755)
</pre>
</code>
</details>

## Reproductions steps
1. Turn on "Do not keep Activities" on Debug Setting
2. Shake the app to display the debug dialog
3. Pressh home button

## Links
- https://console.firebase.google.com/project/confsched2017/monitoring/app/android:io.github.droidkaigi.confsched2017.debug/cluster/6654b602

## Screenshot
N/A

**Comment by hkurokawa** [comment]
I suspect it is due to `CheckDpiStrategy` is not Parcelable and we might have to fix the library.

**Comment by tomoima525** [comment]
Thank you for pointing out!! will fix this and update the library

**Comment by tomoima525** [comment]
I'm currently looking into this issue but I see another crash when I set "Do not keep Activities". Is this known?

```
io.github.droidkaigi.confsched2017.develop.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: io.github.droidkaigi.confsched2017.develop.debug, PID: 17723
                                                                        Theme: themes:{default=overlay:com.cyngn.hexo, iconPack:com.cyngn.hexo fontPkg:com.cyngn.hexo, com.android.systemui=overlay:com.cyngn.hexo com.android.systemui.navbar=overlay:com.cyngn.hexo}
                                                                        java.lang.RuntimeException: Unable to start activit ComponentInfo{io.github.droidkaigi.confsched2017.develop.debug/io.github.droidkaigi.confsche2017.view.activity.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: src.length=1 srcPos=0 dst.length=0 dstPos=0 length=11
                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                  at android.os.Looper.loop(Looper.java:148)
                                                  at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                               Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=11 srcPos=0 dst.length= dstPos=0 length=11
                                                  at java.lang.System.arraycopy(Native Method)
                                                  at org.lucasr.twowayview.widget.ItemEntries.ensureSize(ItemEntries.java:56)
                                                  at org.lucasr.twowayview.widget.ItemEntries.putItemEntry(ItemEntries.java:70)
                                                  a org.lucasr.twowayview.widget.BaseLayoutManager$LanedSavedState.<init>(BaseLayoutManager.ava:597)
                                                  a org.lucasr.twowayview.widget.BaseLayoutManager$LanedSavedState.<init>(BaseLayoutManager.ava:566)
                                                  a org.lucasr.twowayview.widget.BaseLayoutManager$LanedSavedState$1.createFromParcel(BaseLaoutManager.java:628)
                                                  a org.lucasr.twowayview.widget.BaseLayoutManager$LanedSavedState$1.createFromParcel(BaseLaoutManager.java:625)
                                                  at android.os.Parcel.readParcelable(Parcel.java:2367)
                                                  at android.support.v7.widget.RecyclerView$SavedState.<init>(RecyclerView.java:11158)
                                                  a android.support.v7.widget.RecyclerView$SavedState$1.createFromParcel(RecyclerView.java:1183)
                                                  a android.support.v7.widget.RecyclerView$SavedState$1.createFromParcel(RecyclerView.java:1180)
                                                  a android.support.v4.os.ParcelableCompatCreatorHoneycombMR2.createFromParcel(ParcelableComatHoneycombMR2.java:46)
                                                  at android.os.Parcel.readParcelable(Parcel.java:2365)
                                                  at android.os.Parcel.readValue(Parcel.java:2264)
                                                  at android.os.Parcel.readSparseArrayInternal(Parcel.java:2675)
                                                  at android.os.Parcel.readSparseArray(Parcel.java:1967)
                                                  at android.os.Parcel.readValue(Parcel.java:2321)
                                                  at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
                                                                            at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                                  at android.os.Bundle.getSparseParcelableArray(Bundle.java:856)
                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1208)
                                                   android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.jva:128)
                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1608)
                                                  at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2883)
                                                  at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:190)
                                                  at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:353)
                                                  at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
                                                  a io.github.droidkaigi.confsched2017.view.activity.BaseActivity.onCreate(BaseActivity.java49)
                                                  a io.github.droidkaigi.confsched2017.view.activity.MainActivity.onCreate(MainActivity.java39)
                                                  at android.app.Activity.performCreate(Activity.java:6251)
                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510) 
                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                  at android.os.Looper.loop(Looper.java:148) 
                                                  at android.app.ActivityThread.main(ActivityThread.java:5461) 
                                                  at java.lang.reflect.Method.invoke(Native Method)
```

**Comment by konifar** [comment]
@tomoima525 Yes, it's another known issue.
https://github.com/DroidKaigi/conference-app-2017/issues/110

**Comment by hkurokawa** [comment]
@konifar Sorry for disturbing you. But, is it possible to remove the label `welcome contribute`? This bug is derived from another library so I suspect it might be hard for others to solve it in this repository. (Of course, if someone will contribute to that library, it is welcome :-) ) I just want to keep others from wasting time.

If I'm misunderstanding something, feel free to let me know. Thanks.

**Comment by konifar** [comment]
Oh, sorry! I removed the label! Thanks for handling this issue 😃
