### ISSUE TITLE
Crashed when back to MainActivity ("Don't keep Activities" is enabled)

### ISSUE THREAD

**Issue by kikuchy** [DroidKaigi/conference-app-2017#316]
## Overview (Required)
- Enable "Don't keep Activities".
- Open "SponsorsAcrivity" or "ContributorsActivity" form "MainActivity".
- Press Back button, and crashed. Crash report is below.

```java
02-12 17:28:13.084 6157-6157/io.github.droidkaigi.confsched2017.debug E/UncaughtException: java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.droidkaigi.confsched2017.debug/io.github.droidkaigi.confsched2017.view.activity.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: src.length=11 srcPos=0 dst.length=0 dstPos=0 length=11
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
     at android.app.ActivityThread.-wrap11(ActivityThread.java)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:148)
     at android.app.ActivityThread.main(ActivityThread.java:5417)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
  Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=11 srcPos=0 dst.length=0 dstPos=0 length=11
     at java.lang.System.arraycopy(Native Method)
     at org.lucasr.twowayview.widget.ItemEntries.ensureSize(ItemEntries.java:56)
     at org.lucasr.twowayview.widget.ItemEntries.putItemEntry(ItemEntries.java:70)
     at org.lucasr.twowayview.widget.BaseLayoutManager$LanedSavedState.<init>(BaseLayoutManager.java:597)
     at org.lucasr.twowayview.widget.BaseLayoutManager$LanedSavedState.<init>(BaseLayoutManager.java:566)
     at org.lucasr.twowayview.widget.BaseLayoutManager$LanedSavedState$1.createFromParcel(BaseLayoutManager.java:628)
     at org.lucasr.twowayview.widget.BaseLayoutManager$LanedSavedState$1.createFromParcel(BaseLayoutManager.java:625)
     at android.os.Parcel.readParcelable(Parcel.java:2346)
     at android.support.v7.widget.RecyclerView$SavedState.<init>(RecyclerView.java:11158)
     at android.support.v7.widget.RecyclerView$SavedState$1.createFromParcel(RecyclerView.java:11183)
     at android.support.v7.widget.RecyclerView$SavedState$1.createFromParcel(RecyclerView.java:11180)
     at android.support.v4.os.ParcelableCompatCreatorHoneycombMR2.createFromParcel(ParcelableCompatHoneycombMR2.java:46)
     at android.os.Parcel.readParcelable(Parcel.java:2344)
     at android.os.Parcel.readValue(Parcel.java:2243)
     at android.os.Parcel.readSparseArrayInternal(Parcel.java:2653)
     at android.os.Parcel.readSparseArray(Parcel.java:1946)
     at android.os.Parcel.readValue(Parcel.java:2300)
     at android.os.Parcel.readArrayMapInternal(Parcel.java:2592)
     at android.os.BaseBundle.unparcel(BaseBundle.java:221)
     at android.os.Bundle.getSparseParcelableArray(Bundle.java:856)
     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1208)
     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1608)
     at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2883)
     at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:190)
     at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:353)
     at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
     at io.github.droidkaigi.confsched2017.view.activity.BaseActivity.onCreate(BaseActivity.java:49)
     at io.github.droidkaigi.confsched2017.view.activity.MainActivity.onCreate(MainActivity.java:39)
     at android.app.Activity.performCreate(Activity.java:6237)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:148) 
     at android.app.ActivityThread.main(ActivityThread.java:5417) 
     at java.lang.reflect.Method.invoke(Native Method) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

## Links

n/a

## Screenshot
n/a

**Comment by konifar** [comment]
:eyes:

**Comment by konifar** [comment]
Thanks for report!
Is this same with https://github.com/DroidKaigi/conference-app-2017/issues/110 ?

**Comment by kikuchy** [comment]
Oh, it's maybe same with #110.
Sorry for repeating 😭

**Comment by konifar** [comment]
No problem! It's better than missing the bug 😉 
Okay, I'll close this. I appreciate you! Thanks!
